[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contract = "FtX5sPSgTzSoefKZaeAqBuaYDUWKREUpiDNxFLsScEH2"

[registry]
url = "http://localhost:8899/"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
